"""initial schema

Revision ID: a45796700ed4
Revises: 
Create Date: 2026-09-02 16:23:03.879618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45796700ed4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('feature', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_llm_cache_key')
    )
    op.create_index(op.f('ix_llm_cache_feature'), 'llm_cache', ['feature'], unique=False)
    op.create_table('user',
    sa.Column('native_language', sa.String(length=10), nullable=True),
    sa.Column('cefr_level', sa.String(length=5), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('books',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_user_id'), 'books', ['user_id'], unique=False)
    op.create_table('highlights',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('cfi_range', sa.String(length=2048), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highlights_book_id'), 'highlights', ['book_id'], unique=False)
    op.create_index(op.f('ix_highlights_user_id'), 'highlights', ['user_id'], unique=False)
    op.create_table('reading_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('cfi_position', sa.String(length=1024), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_reading_state_user_book')
    )
    op.create_index(op.f('ix_reading_state_book_id'), 'reading_state', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_state_user_id'), 'reading_state', ['user_id'], unique=False)
    op.create_table('vocab_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('book_id', sa.Uuid(), nullable=False),
    sa.Column('phrase', sa.String(length=512), nullable=False),
    sa.Column('context_sentence', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocab_entries_book_id'), 'vocab_entries', ['book_id'], unique=False)
    op.create_index(op.f('ix_vocab_entries_user_id'), 'vocab_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_entries_user_id'), table_name='vocab_entries')
    op.drop_index(op.f('ix_vocab_entries_book_id'), table_name='vocab_entries')
    op.drop_table('vocab_entries')
    op.drop_index(op.f('ix_reading_state_user_id'), table_name='reading_state')
    op.drop_index(op.f('ix_reading_state_book_id'), table_name='reading_state')
    op.drop_table('reading_state')
    op.drop_index(op.f('ix_highlights_user_id'), table_name='highlights')
    op.drop_index(op.f('ix_highlights_book_id'), table_name='highlights')
    op.drop_table('highlights')
    op.drop_index(op.f('ix_books_user_id'), table_name='books')
    op.drop_table('books')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_llm_cache_feature'), table_name='llm_cache')
    op.drop_table('llm_cache')
    # ### end Alembic commands ###
